<?php

/**
 * @file
 * Hooks implementations for the APC Storage - Admin pages module.
 */

declare(strict_types=1);

/**
 * Implements hook_permission().
 */
function apc_storage_admin_permission(): array {
  return array(
    'access APC Storage data' => array(
      'title' => t('Access APC Storage data'),
      'description' => t('Allows access to the APC Storage reports.'),
    ),
  );
}

/**
 * Implements hook_page_alter().
 */
function apc_storage_admin_page_alter(&$page): void {
  if (variable_get('apc_storage_show_details', FALSE) && user_access('access APC Storage data')) {
    $operations = ApcStorageCache::operations();
    $rows = array();

    if (!empty($operations)) {
      foreach ($operations as $operation) {
        $row = array(
          $operation['method'],
          $operation['bin'],
          $operation['cids'],
        );

        if (is_array($row[2])) {
          $row[2] = implode(',<br />', $row[2]);
        }

        $rows[] = $row;
      }
    }

    $page['page_top']['apc_storage_cache_info'] = array(
      '#type' => 'markup',
      '#prefix' => '<div class="apc-storage-admin-cache-info">',
      '#suffix' => '</div>',
      '#markup' => '<h2>' . t('APCu information') . '</h2>',
    );

    $page['page_bottom']['apc_storage_admin_cache_info']['operations'] = array(
      '#type' => 'table',
      '#header' => array(t('Operation'), t('Bin'), t('Cache IDs')),
      '#rows' => $rows,
      '#empty' => t('No APC cache operations have been performed.'),
    );

    drupal_page_is_cacheable(FALSE);
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for system_performance_settings().
 */
function apc_storage_admin_form_system_performance_settings_alter(&$form, &$form_state): void {
  if (extension_loaded('apcu')) {
    $form['clear_cache']['clear']['#submit'][] = 'apc_storage_admin_clear_apcu_cache';

    $form['clear_cache']['apc_storage_admin_apcu_cache'] = array(
      '#type' => 'submit',
      '#value' => t('Clear APCu cache'),
      '#submit' => array('apc_storage_admin_clear_apcu_cache'),
    );
  }
}

/**
 * Submission form handler for system_performance_settings().
 */
function apc_storage_admin_clear_apcu_cache(): void {
  if (ApcStorageCache::deleteAllStoredData()) {
    drupal_set_message(t('The APCu cache has been cleared.'));
  }
  else {
    drupal_set_message(t('The APCu cache could not be cleared.'), 'error');
  }
}
