<?php

/**
 * @file
 * Hook implementations for the Alternative PHP Cache module.
 */

// phpcs:disable SlevomatCodingStandard.ControlStructures.RequireNullCoalesceOperator.NullCoalesceOperatorNotUsed

/**
 * Implements hook_init().
 */
function apc_init() {
  global $user;

  if (($user->uid == 0) || !variable_get('apc_show_debug', FALSE)
      || !user_access('access apc statistics') || strstr($_SERVER['PHP_SELF'], 'update.php')
      || strstr($_GET['q'], 'autocomplete')) {
    return;
  }

  drupal_register_shutdown_function('apc_shutdown');
}

/**
 * Implements hook_permission().
 */
function apc_permission() {
  return array(
    'access apc statistics' => array(
      'title' => t('Access APC statistics'),
      'description' => t('Allows access to the APC statistics reports.'),
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter() for system_performance_settings().
 */
function apc_form_system_performance_settings_alter(&$form, $form_state) {
  if (extension_loaded('apcu')) {
    $form['clear_cache']['clear']['#submit'][] = 'apc_clear_apcu_cache';

    $form['clear_cache']['apcu_cache'] = array(
      '#type' => 'submit',
      '#value' => t('Clear APCu cache'),
      '#submit' => array('apc_clear_apcu_cache'),
    );
  }
}

/**
 * Submission form handler for system_performance_settings().
 */
function apc_clear_apcu_cache() {
  // apcu_clear_cache() always return TRUE; that is why we show a single message
  // without checking the return value.
  apcu_clear_cache();
  drupal_set_message(t('APCu cache has been cleared.'));
}

/**
 * Implements hook_xmlrpc().
 */
function apc_xmlrpc() {
  $methods[] = array(
    'apc.clear_cache',
    'apc_clear_cache',
    array(
      'array',
      'string',
      'array',
    ),
    t('Clears the APCu cache.'),
  );

  return $methods;
}

/**
 * XML-RPC callback to clear the cache.
 *
 * @see apc_xmlrpc()
 */
function apc_clear_cache($key, $bins = array()) {
  if (empty($key) || variable_get('cron_key', 'drupal') != $key) {
    watchdog('apc', 'An invalid key was passed to apc_clear_cache().', array(), WATCHDOG_ERROR);

    return array(
      'success' => FALSE,
      'message' => t('Invalid key for apc.clear_cache.'),
    );
  }

  // Clear the APCu cache.
  foreach ($bins as $bin => $cids) {
    foreach ($cids as $cid => $wildcard) {
      // $cid has been serialized in DrupalAPCCache::clear().
      cache_clear_all(unserialize($cid), $bin, $wildcard);
    }
  }

  return array(
    'success' => TRUE,
    'message' => t('The cache has been cleared.'),
  );
}

/**
 * Shutdown function: Displays APC stats in the footer.
 */
function apc_shutdown() {
  global $_apc_statistics;

  // Don't call theme() during shutdown if the registry has been rebuilt (such
  // as when enabling/disabling modules on admin/build/modules) as things break.
  // Instead, simply exit without displaying admin statistics for this page
  // load.  See http://drupal.org/node/616282 for discussion.
  if (!function_exists('theme_get_registry') || !theme_get_registry()) {
    return;
  }

  // Try not to break non-HTML pages.
  if (function_exists('drupal_get_http_header')) {
    $header = drupal_get_http_header('content-type');
    if ($header) {
      $formats = array('xml', 'javascript', 'json', 'plain', 'image', 'application', 'csv', 'x-comma-separated-values');
      foreach ($formats as $format) {
        if (strstr($header, $format)) {
          return;
        }
      }
    }
  }

  if (isset($_apc_statistics) && is_array($_apc_statistics)) {
    print '<div id="apc-devel"><h2>' . t('APC statistics') . '</h2>';
    $rows = array();

    foreach ($_apc_statistics as $row) {
      if (is_array($row[2])) {
        $row[2] = implode(',<br />', $row[2]);
      }
      $rows[] = $row;
    }
    print theme('table', array(
      'header' => array(('Type'), t('Bin'), t('Cid(s)')),
      'rows' => $rows,
    ));
    print '</div>';
  }
}
