<?php

/**
 * @file
 * Hook implementations for the Alternative PHP Cache module.
 */

// phpcs:disable SlevomatCodingStandard.ControlStructures.RequireNullCoalesceOperator.NullCoalesceOperatorNotUsed

/**
 * Implements hook_permission().
 */
function apc_permission() {
  return array(
    'access apc statistics' => array(
      'title' => t('Access APC statistics'),
      'description' => t('Allows access to the APC statistics reports.'),
    ),
  );
}

/**
 * Implements hook_page_alter().
 */
function apc_page_alter(&$page) {
  if (variable_get('apc_show_debug', FALSE) && user_access('access apc statistics')) {
    $operations = DrupalApcCache::operations();
    $rows = array();

    if (!empty($operations) && is_array($operations)) {
      foreach ($operations as $row) {
        if (is_array($row[2])) {
          $row[2] = implode(',<br />', $row[2]);
        }

        $rows[] = $row;
      }
    }

    $page['page_top']['apc_cache_info'] = array(
      '#type' => 'markup',
      '#prefix' => '<div class="apc-cache-info">',
      '#suffix' => '</div>',
      '#markup' => '<h2>' . t('APCu information') . '</h2>',
    );

    $page['page_bottom']['apc_cache_info']['operations'] = array(
      '#type' => 'table',
      '#header' => array(t('Operation'), t('Bin'), t('Cache IDs')),
      '#rows' => $rows,
      '#empty' => t('No APC cache operations have been performed.'),
    );

    drupal_page_is_cacheable(FALSE);
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for system_performance_settings().
 */
function apc_form_system_performance_settings_alter(&$form, $form_state) {
  if (extension_loaded('apcu')) {
    $form['clear_cache']['clear']['#submit'][] = 'apc_clear_apcu_cache';

    $form['clear_cache']['apcu_cache'] = array(
      '#type' => 'submit',
      '#value' => t('Clear APCu cache'),
      '#submit' => array('apc_clear_apcu_cache'),
    );
  }
}

/**
 * Submission form handler for system_performance_settings().
 */
function apc_clear_apcu_cache() {
  if (apcu_enabled()) {
    $iterator = new APCUIterator("/^apc_cache_/", APC_ITER_KEY);

    if (apcu_delete($iterator)) {
      drupal_set_message(t('The APCu cache has been cleared.'));
    }
    else {
      drupal_set_message(t('The APCu cache could not be cleared.'), 'error');
    }
  }
  else {
    drupal_set_message(t('APCu is not enabled.'), 'warning');
  }
}

/**
 * Implements hook_xmlrpc().
 */
function apc_xmlrpc() {
  $methods[] = array(
    'apc.clear_cache',
    'apc_clear_cache',
    array(
      'boolean',
      'string',
      'array',
    ),
    t('Clears the APCu cache.'),
  );

  return $methods;
}

/**
 * XML-RPC callback to clear the cache.
 *
 * @see apc_xmlrpc()
 */
function apc_clear_cache($key, $bins = array()) {
  if (empty($key) || variable_get('cron_key', 'drupal') != $key) {
    watchdog('apc', 'An invalid auth key was passed to apc_clear_cache().', array(), WATCHDOG_ERROR);

    return xmlrpc_error(-32602, t('Invalid auth key for apc.clear_cache.'));
  }

  // Clear the APCu cache.
  foreach ($bins as $bin => $cids) {
    foreach ($cids as $cid => $wildcard) {
      // $cid has been serialized in DrupalAPCCache::clear().
      cache_clear_all(unserialize($cid), $bin, $wildcard);
    }
  }

  return TRUE;
}
