<?php

/**
 * @file
 * Install, update, and uninstall hooks for the Alternative PHP Cache module.
 */

declare(strict_types=1);

// phpcs:disable SlevomatCodingStandard.ControlStructures.RequireNullCoalesceOperator.NullCoalesceOperatorNotUsed

/**
 * Deletes APCu keys based on the provided patterns.
 *
 * It stores the list of keys to remove in a persistent variable, to be able to
 * delete then later, in the case the APCu extension is not available.
 *
 * @param array $patterns
 *   An associative array of patterns and their corresponding old patterns. Old
 *   patterns are replaced by the new patterns.
 */
function _apc_delete_apcu_keys($patterns = array()) {
  $apcu_keys_to_remove = variable_get('apc_apcu_keys_to_remove', array());

  foreach ($patterns as $pattern => $old_pattern) {
    if (!empty($old_pattern) && isset($apcu_keys_to_remove[$old_pattern])) {
      unset($apcu_keys_to_remove[$old_pattern]);
    }

    $apcu_keys_to_remove[$pattern] = TRUE;
  }

  // Update the persistent variable, just in case an error does not allow the
  // code to terminate.
  variable_set('apc_apcu_keys_to_remove', $apcu_keys_to_remove);

  if (extension_loaded('apcu') && apcu_enabled()) {
    foreach (array_keys($apcu_keys_to_remove) as $pattern) {
      $pattern = '/^' . preg_quote($pattern, '/') . '/';
      $iterator = new APCUIterator($pattern, APC_ITER_KEY);

      apcu_delete($iterator);
      unset($apcu_keys_to_remove[$pattern]);
    }

    variable_set('apc_apcu_keys_to_remove', $apcu_keys_to_remove);
  }
}

/**
 * Implements hook_requirements().
 */
function apc_requirements($phase) {
  // Ensure translations don't break at install time.
  $t = get_t();

  $requirements['apc'] = array(
    'title' => $t('APCu extension'),
  );

  if (extension_loaded('apcu')) {
    $apcu_version = phpversion('apcu');

    if ($apcu_version === FALSE) {
      $severity = drupal_is_cli() ? REQUIREMENT_INFO : REQUIREMENT_ERROR;
      $requirements['apc']['description'] = $t(
        'The Alternative PHP Cache module needs the APCu extension to be enabled.'
      );
      $requirements['apc']['severity'] = $severity;

      return $requirements;
    }

    $required_version_installed = version_compare($apcu_version, '5.1.17', '>=');

    if (!$required_version_installed) {
      $requirements['apc']['description'] = $t(
        'The Alternative PHP Cache module needs the APCu extension version 5.1.17 or higher; version %apcu_version is currently installed.',
        array('%apcu_version' => $apcu_version)
      );
      $requirements['apc']['severity'] = REQUIREMENT_ERROR;

      return $requirements;
    }

    if (apcu_enabled() && $phase == 'runtime') {
      $cache = apcu_cache_info(TRUE);
      $num_entries = $cache['num_entries'] ?? 0;
      $start_time = $cache['start_time'] ?? time();
      $mem_size = $cache['mem_size'] ?? 0;

      $requirements['apc']['description'] = $t(
        'The APCu extension has been running for !duration. It contains !num_entries entries and uses !memory_size of memory.',
        array(
          '!duration' => format_interval(time() - $start_time),
          '!num_entries' => $num_entries,
          '!memory_size' => format_size($mem_size),
        )
      );
      $requirements['apc']['severity'] = REQUIREMENT_INFO;
    }
    elseif (!apcu_enabled()) {
      $severity = drupal_is_cli() ? REQUIREMENT_INFO : REQUIREMENT_ERROR;
      $requirements['apc']['description'] = $t(
        'The Alternative PHP Cache module needs the APCu extension to be enabled.'
      );
      $requirements['apc']['severity'] = $severity;
    }
  }
  else {
    $requirements['apc']['description'] = $t(
      'The Alternative PHP Cache module needs the <a href="!apcu_link">APCu</a> extension.',
      array('!apcu_link' => 'https://www.php.net/apcu')
    );
    $requirements['apc']['severity'] = REQUIREMENT_ERROR;
  }

  return $requirements;
}

/**
 * Implements hook_last_removed().
 */
function apc_last_removed() {
  return 7107;
}

/**
 * Clear the APCu storage to remove the keys using the old prefix.
 */
function apc_update_7200() {
  _apc_delete_apcu_keys();

  if (extension_loaded('apcu') && apcu_enabled()) {
    apcu_clear_cache();
  }
}

/**
 * Update the registry to include the renamed classes.
 */
function apc_update_7201() {
  registry_rebuild();
}

/**
 * Implements hook_uninstall().
 */
function apc_uninstall() {
  if (extension_loaded('apcu') && apcu_enabled()) {
    $cache_iterator = new APCUIterator('/^apc_cache::[a-zA-Z0-9-_]{40,46}::[0-9a-f]{2,}/', APC_ITER_KEY);
    $lock_iterator = new APCUIterator('/^apc_lock::[a-zA-Z0-9-_]{40,46}/', APC_ITER_KEY);

    // Delete all the APCu keys used by the module.
    apcu_delete($cache_iterator);
    apcu_delete($lock_iterator);
    apcu_delete('apc_cache::default_prefix');
  }

  // Deleted all the persistent variables used by the module.
  variable_del('apc_apcu_keys_to_remove');
}
