<?php

/**
 * @file
 * Install, update, and uninstall hooks for the Alternative PHP Cache module.
 */

// phpcs:disable SlevomatCodingStandard.ControlStructures.RequireNullCoalesceOperator.NullCoalesceOperatorNotUsed

/**
 * Implements hook_requirements().
 */
function apc_requirements($phase) {
  // Ensure translations don't break at install time.
  $t = get_t();

  $requirements['apc'] = array(
    'title' => $t('APCu extension'),
  );

  if (extension_loaded('apcu')) {
    $apcu_version = phpversion('apcu');
    $required_version_installed = version_compare($apcu_version, '5.0.0') >= 0;

    if (!$required_version_installed) {
      $requirements['apc']['description'] = $t(
        'The Alternative PHP Cache module needs the APCu extension version 5.0.0 or higher; version %apcu_version is currently installed.',
        array('%apcu_version' => $apcu_version)
      );
      $requirements['apc']['severity'] = REQUIREMENT_ERROR;

      return $requirements;
    }

    if (apcu_enabled() && $phase == 'runtime') {
      $cache = apcu_cache_info(TRUE);
      $num_entries = isset($cache['num_entries']) ? $cache['num_entries'] : 0;
      $start_time = isset($cache['start_time']) ? $cache['start_time'] : time();
      $mem_size = isset($cache['mem_size']) ? $cache['mem_size'] : 0;

      $requirements['apc']['description'] = $t(
        'The APCu extension has been running for !duration. It contains !num_entries entries and uses !memory_size of memory.',
        array(
          '!duration' => format_interval(time() - $start_time),
          '!num_entries' => $num_entries,
          '!memory_size' => format_size($mem_size),
        )
      );
      $requirements['apc']['severity'] = REQUIREMENT_INFO;
    }
    elseif (!apcu_enabled()) {
      $severity = drupal_is_cli() ? REQUIREMENT_INFO : REQUIREMENT_ERROR;
      $requirements['apc']['description'] = $t(
        'The Alternative PHP Cache module needs the APCu extension to be enabled.'
      );
      $requirements['apc']['severity'] = $severity;
    }
  }
  else {
    $requirements['apc']['description'] = $t(
      'The Alternative PHP Cache module needs the <a href="!apcu_link">APCu</a> extension.',
      array('!apcu_link' => 'https://www.php.net/apcu')
    );
    $requirements['apc']['severity'] = REQUIREMENT_ERROR;
  }

  return $requirements;
}

/**
 * Clear the APCu storage since the prefix used for the cache bins has changed.
 */
function apc_update_7101() {
  apcu_clear_cache();
}

/**
 * Delete the APCu keys starting with apc_cache_ as they are no longer used.
 */
function apc_update_7102() {
  $apcu_enabled = extension_loaded('apcu') && apcu_enabled();

  if ($apcu_enabled && class_exists('APCUIterator')) {
    $iterator = new APCUIterator('/^apc_cache_/', APC_ITER_KEY);
    apcu_delete($iterator);
  }
}

/**
 * Rebuild the code registry, as a class file has been moved.
 */
function apc_update_7103() {
  registry_rebuild();
}

/**
 * Delete the APCu keys starting with apc_cache:: to create the new keys.
 */
function apc_update_7104() {
  $apcu_enabled = extension_loaded('apcu') && apcu_enabled();

  if ($apcu_enabled && class_exists('APCUIterator')) {
    $iterator = new APCUIterator('/^apc_cache::/', APC_ITER_KEY);
    apcu_delete($iterator);
  }
}

/**
 * Implements hook_uninstall().
 */
function apc_uninstall() {
  $apcu_enabled = extension_loaded('apcu') && apcu_enabled();

  if ($apcu_enabled && class_exists('APCUIterator')) {
    $iterator = new APCUIterator('/^apc_cache::/', APC_ITER_KEY);
    apcu_delete($iterator);
  }
}
