<?php

/**
 * @file
 * Hook implementations for the APC Storage module.
 */

/**
 * Implements hook_autoload_info().
 *
 * @hook
 */
function apc_storage_autoload_info(): array {
  return [
    'apc_storage\cache\Cache' => 'includes/cache.class.inc',
    'apc_storage\cache\ChainedCache' => 'includes/chained_cache.class.inc',
    'apc_storage\cache\DatabaseCache' => 'includes/database_cache.class.inc',
    'apc_storage\lock\Lock' => 'includes/lock.class.inc',
    'apc_storage\queue\Queue' => 'includes/queue.class.inc',
  ];
}
