<?php

/**
 * @file
 * Hook implementations for the APC Storage module.
 */

/**
 * Implements hook_autoload_info().
 *
 * @hook
 */
function apc_storage_autoload_info(): array {
  return [
    'Cache' => 'includes/apc_storage_cache.class.inc',
    'ChainedCache' => 'includes/apc_chained_cache.class.inc',
    'Lock' => 'includes/apc_storage_lock.class.inc',
    'ApcStorageLogger' => 'includes/apc_storage_logger.class.inc',
    'Queue' => 'includes/apc_storage_queue.class.inc',
  ];
}
