<?php

/**
 * @file
 * Hook implementations for the APC Storage Queue Test Support module.
 */

/**
 * Implements hook_cron_queue_info().
 */
function apc_storage_queue_test_support_cron_queue_info() {
  $queues['apc_storage_queue_test_support_class_callback'] = array(
    'worker callback' => array('ApcStorageQueueTestSupportWorker', 'cronQueueTestCallback'),
  );
  $queues['apc_storage_queue_test_support_function_callback'] = array(
    'worker callback' => 'apc_storage_queue_test_support_callback',
  );

  return $queues;
}

function apc_storage_queue_test_support_callback() {
  // This function is intentionally left empty.
}

/**
 * Worker class for the queue tests.
 */
class ApcStorageQueueTestSupportWorker {

  /**
   * Callback function for processing queue items during cron runs.
   */
  static public function cronQueueTestCallback() {
    // This method is intentionally left empty.
  }

}
