<?php

/**
 * @file
 * Hooks implementations for the APC Storage - Admin Pages module.
 */

declare(strict_types=1);

use apc_storage\Cache\ApcuBackend;

function apc_storage_admin_menu(): array {
  return array(
    'admin/config/development/apc_storage' => array(
      'title' => t('Enable the APC Storage debug mode and other settings.'),
      'page callback' => 'backdrop_get_form',
      'page arguments' => array('apc_storage_admin_settings'),
      'access arguments' => array('administer APC Storage settings'),
    ),
  );
}

/**
 * Implements hook_permission().
 */
function apc_storage_admin_permission(): array {
  return array(
    'access APC Storage reports' => array(
      'title' => t('Access APC Storage reports'),
      'description' => t('Allows the access to APC Storage reports.'),
    ),
    'administer APC Storage settings' => array(
      'title' => t('Administer APC Storage settings'),
      'description' => t('Allow to enable the APC Storage reports and change other settings.'),
    )
  );
}

/**
 * Implements hook_page_alter().
 */
function apc_storage_admin_page_alter(&$page): void {
  if (config_get('apc_storage.admin', 'gather_debug_info') && user_access('access APC Storage reports')) {
    $operations = ApcuBackend::operations();
    $rows = array();

    if (!empty($operations)) {
      foreach ($operations as $operation) {
        $row = array(
          $operation['method'],
          $operation['bin'],
          $operation['cids'],
        );

        if (is_array($row[2])) {
          $row[2] = implode(',<br />', $row[2]);
        }

        $rows[] = $row;
      }
    }

    $page['page_top']['apc_storage_cache_info'] = array(
      '#type' => 'markup',
      '#prefix' => '<div class="apc-storage-admin-cache-info">',
      '#suffix' => '</div>',
      '#markup' => '<h2>' . t('APCu information') . '</h2>',
    );

    $page['page_bottom']['apc_storage_admin_cache_info']['operations'] = array(
      '#type' => 'table',
      '#header' => array(t('Operation'), t('Bin'), t('Cache IDs')),
      '#rows' => $rows,
      '#empty' => t('No APC cache operations have been performed.'),
    );

    backdrop_page_is_cacheable(FALSE);
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for system_performance_settings().
 */
function apc_storage_admin_form_system_performance_settings_alter(&$form, &$form_state): void {
  if (extension_loaded('apcu') && apcu_enabled()) {
    $form['clear_cache']['apc_storage_admin_apcu_cache'] = array(
      '#type' => 'submit',
      '#value' => t('Clear APCu cache'),
      '#submit' => array('apc_storage_admin_clear_apcu_cache'),
    );
  }
}

/**
 * Submission form handler for system_performance_settings().
 */
function apc_storage_admin_clear_apcu_cache(): void {
  if (ApcuBackend::deleteAllStoredData()) {
    backdrop_set_message(t('The APCu cache has been cleared.'));
  }
  else {
    backdrop_set_message(t('The APCu cache could not be cleared.'), 'error');
  }
}

/**
 * Form builder; Configure the APC Storage settings.
 */
function apc_storage_admin_settings($form, &$form_state): array {
  $config = config('apc_storage.admin');

  $form['#config'] = 'apc_storage.admin';

  $description = t('User accounts with the %permission permission will see which data is stored in the APCu storage.',
    array(
    '%permission' => l(t('Access APC Storage reports'), 'admin/config/people/permissions', array('fragment' => 'module-apc-storage-admin')),
    )
  );
  $description .= ' ';
  $description .= t('This setting should be used only for debugging purposes. It should not be enabled in production, since it increases the memory usage and it can cause performance issues.');
  $form['gather_debug_info'] = array(
    '#type' => 'checkbox',
    '#title' => t('Gather information about which data is stored in the APCu storage'),
    '#description' => $description,
    '#default_value' => $config->get('gather_debug_info'),
  );

  return system_settings_form($form);
}
