<?php

/**
 * @file
 * Hooks implementations for the APC Storage Admin Pages module.
 */

declare(strict_types=1);

/**
 * Implements hook_permission().
 */
function apc_storage_admin_permission(): array {
  return array(
    'access APC Storage reports' => array(
      'title' => t('Access APC Storage reports'),
      'description' => t('Allows the access to APC Storage reports.'),
    ),
    'administer APC Storage settings' => array(
      'title' => t('Administer APC Storage settings'),
      'description' => t('Allow to enable the APC Storage reports and change other settings.'),
    )
  );
}

/**
 * Implements hook_page_alter().
 */
function apc_storage_admin_page_alter(&$page): void {
  if (user_access('access APC Storage reports')) {
    // @todo Rewrite this code after the new API is ready.
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for system_performance_settings().
 */
function apc_storage_admin_form_system_performance_settings_alter(&$form, &$form_state): void {
  if (extension_loaded('apcu') && apcu_enabled()) {
    $form['clear_cache']['apc_storage_admin_apcu_cache'] = array(
      '#type' => 'submit',
      '#value' => t('Clear APCu cache'),
      '#submit' => array('apc_storage_admin_clear_apcu_cache'),
    );
  }
}

/**
 * Submission form handler for system_performance_settings().
 */
function apc_storage_admin_clear_apcu_cache(): void {
  if (extension_loaded('apcu') && apcu_enabled()) {
    $regex = '/^(apc_storage_cache|apc_storage_chained_cache)::/';

    if (apcu_delete(new APCUIterator($regex))) {
      backdrop_set_message(t('The APCu cache has been cleared.'));
    }
    else {
      backdrop_set_message(t('The APCu cache could not be cleared.'), 'error');
    }
  }
  else {
    backdrop_set_message(t('The APCu extension is not enabled.'), 'warning');
  }
}
