name: Simpletest
on:
  pull_request:
    paths-ignore: [ '.editorconfig', '.gitattributes', '**.md', '**.txt' ]
    branches: [ '1.*' ]
  push:
    paths-ignore: [ '.editorconfig', '.gitattributes', '**.md', '**.txt' ]
    branches: [ '1.*' ]
jobs:
  simpletest:
    name: Test code
    runs-on: ubuntu-22.04
    # Skip this job if the PR title contains "[skip tests]".
    if: ${{ !contains(github.event.pull_request.title, '[skip tests]') }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        php-versions: [ '8.3', '8.4' ]
        database-versions: [ 'mariadb-10.3' ]
    steps:
      - name: Set up environment variables
        run: |
          echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      - name: Install MariaDB
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: ${{ matrix.database-versions }}
          root-password: 'root'
          auto-start: true
      - name: Verify setup and create database
        run: |
          echo -e '[client]\nuser = root\npassword = root\nhost = 127.0.0.1' > ~/.my.cnf
          mysql -e 'SELECT version()\G'
          mysql -e 'CREATE DATABASE backdrop;'
      - name: Check out Backdrop core
        uses: actions/checkout@v4
        with:
          repository: backdrop/backdrop
      - name: Check out module
        uses: actions/checkout@v4
        with:
          path: modules/${{ env.REPOSITORY_NAME }}
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: apcu
          ini-values: apc.enabled=1, apc.enable_cli=1, apc.entries_hint = 4096, apc.shm_segments = 1, apc.shm_size = 32M, apc.gc_ttl=3600, apc.ttl = 0
          coverage: none
      - name: Set up Apache
        run: |
          sudo cp -f modules/${{ env.REPOSITORY_NAME }}/.github/misc/default.conf /etc/apache2/sites-available/000-default.conf
          sudo sed -i -e "s?_PWD?$PWD?g" -e "s/_PHP_VERSION/${{ matrix.php-versions }}/g" /etc/apache2/sites-available/000-default.conf
          sudo apt-get install libapache2-mod-fcgid
          sudo a2enmod rewrite proxy fcgid proxy_fcgi
          sudo systemctl start apache2.service
          sudo sed -i -e 's/user = www-data/user = runner/' /etc/php/${{ matrix.php-versions }}/fpm/pool.d/www.conf
          sudo sed -i -e 's/listen.owner = www-data/listen.owner = runner/' /etc/php/${{ matrix.php-versions }}/fpm/pool.d/www.conf
          sudo systemctl restart php${{ matrix.php-versions }}-fpm.service
      - name: Install Backdrop
        run: |
          cp modules/${{ env.REPOSITORY_NAME }}/.github/misc/settings.local.php .
          core/scripts/install.sh --db-url=mysql://root:root@127.0.0.1/backdrop
      - name: Run tests
        run: core/scripts/run-tests.sh --force --directory=modules/${{ env.REPOSITORY_NAME }} --verbose --color --concurrency=7 --cache 2>&1
